name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root_shop
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        run: docker-compose build

      - name: Start Docker containers
        run: docker-compose up -d

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: docker-compose exec app composer install

      - name: Run migrations
        run: docker-compose exec app php artisan migrate

      - name: Seed the database
        run: docker-compose exec app php artisan db:seed

      - name: Run tests
        run: docker-compose exec app php artisan test
